/** Google Places primary types — https://developers.google.com/maps/documentation/places/web-service/place-types */
export const PLACE_CATEGORIES = [
  { value: "", label: "All businesses" },
  { value: "restaurant", label: "Restaurant" },
  { value: "cafe", label: "Cafe" },
  { value: "bar", label: "Bar" },
  { value: "bakery", label: "Bakery" },
  { value: "grocery_store", label: "Grocery store" },
  { value: "supermarket", label: "Supermarket" },
  { value: "clothing_store", label: "Clothing store" },
  { value: "electronics_store", label: "Electronics" },
  { value: "furniture_store", label: "Furniture" },
  { value: "home_goods_store", label: "Home goods" },
  { value: "hardware_store", label: "Hardware" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "hospital", label: "Hospital" },
  { value: "dentist", label: "Dentist" },
  { value: "doctor", label: "Doctor" },
  { value: "veterinary_care", label: "Veterinary" },
  { value: "gym", label: "Gym" },
  { value: "spa", label: "Spa" },
  { value: "beauty_salon", label: "Beauty salon" },
  { value: "hair_salon", label: "Hair salon" },
  { value: "lawyer", label: "Law firm" },
  { value: "accounting", label: "Accounting" },
  { value: "real_estate_agency", label: "Real estate" },
  { value: "insurance_agency", label: "Insurance" },
  { value: "car_dealer", label: "Car dealer" },
  { value: "car_repair", label: "Auto repair" },
  { value: "gas_station", label: "Gas station" },
  { value: "lodging", label: "Hotel / lodging" },
  { value: "school", label: "School" },
  { value: "university", label: "University" },
  { value: "bank", label: "Bank" },
  { value: "atm", label: "ATM" },
  { value: "plumber", label: "Plumber" },
  { value: "electrician", label: "Electrician" },
  { value: "roofing_contractor", label: "Roofing" },
  { value: "general_contractor", label: "Contractor" },
  { value: "moving_company", label: "Moving company" },
  { value: "storage", label: "Storage" },
  { value: "florist", label: "Florist" },
  { value: "pet_store", label: "Pet store" },
] as const;
