export {
  type GeoCity,
  type GeoProvince,
  type GeoRegion,
  type GeoSearchContext,
  countryHasGeoHierarchy,
  getRegionsForCountry,
  getRegion,
  getProvincesForRegion,
  getProvincesForCountry,
  getProvince,
  getProvinceByCode,
  getCitiesForProvince,
  getCity,
  MAX_PROVINCE_SEARCH_ANCHORS,
  resolveSearchAnchors,
  buildGeoLocationLabel,
  resolveGeoSearchContext,
  requiresProvinceSelection,
  isGeoSelectionComplete,
} from "@am2/shared";
